import { DocumentType } from '../types';

export interface DocumentTypeConfig {
  type: DocumentType;
  label: string;
  shortLabel: string;
  supportsBack: boolean;
  frontLabel: string;
  frontDescription: string;
  backLabel?: string;
  backDescription?: string;
  iconName: string;
  expectedFrontFields: string[];
  expectedBackFields?: string[];
}

export const DOCUMENT_TYPE_CONFIGS: Record<DocumentType, DocumentTypeConfig> = {
  'AADHAAR_CARD': {
    type: 'AADHAAR_CARD',
    label: 'Aadhaar Card (UIDAI)',
    shortLabel: 'Aadhaar Card',
    supportsBack: true,
    frontLabel: 'Aadhaar Front Side',
    frontDescription: 'Cardholder Name, 12-digit Aadhaar Number, DOB/YOB, Gender & Photo',
    backLabel: 'Aadhaar Back Side & Address',
    backDescription: 'Multi-line Residential Address, C/O, District, State, PIN Code & QR',
    iconName: 'ShieldCheck',
    expectedFrontFields: ['fullName', 'documentNumber', 'dob', 'gender'],
    expectedBackFields: ['address', 'pinCode', 'district', 'state'],
  },
  'PAN_CARD': {
    type: 'PAN_CARD',
    label: 'PAN Card (Income Tax Dept)',
    shortLabel: 'PAN Card',
    supportsBack: true,
    frontLabel: 'PAN Front Side',
    frontDescription: 'PAN Number (ABCDE1234F), Cardholder Name, Father\'s Name, DOB & Photo',
    backLabel: 'PAN Back Side / Address',
    backDescription: 'Address details, QR/barcode, or reverse document side',
    iconName: 'CreditCard',
    expectedFrontFields: ['documentNumber', 'fullName', 'fatherName', 'dob'],
    expectedBackFields: ['address', 'pinCode'],
  },
  'DRIVING_LICENCE': {
    type: 'DRIVING_LICENCE',
    label: 'Driving Licence (RTO / MoRTH)',
    shortLabel: 'Driving Licence',
    supportsBack: true,
    frontLabel: 'Licence Front Side',
    frontDescription: 'DL Number, Full Name, DOB, Issue Date, Validity & Photo',
    backLabel: 'Licence Back Side',
    backDescription: 'Residential Address, Authorized Vehicle Classes & Endorsements',
    iconName: 'Car',
    expectedFrontFields: ['documentNumber', 'fullName', 'dob', 'expiryDate'],
    expectedBackFields: ['address'],
  },
  'VOTER_ID': {
    type: 'VOTER_ID',
    label: 'Voter ID Card (EPIC - ECI)',
    shortLabel: 'Voter ID (EPIC)',
    supportsBack: true,
    frontLabel: 'Voter ID Front Side',
    frontDescription: 'EPIC Number, Cardholder Name, Father/Husband Name, Gender & Photo',
    backLabel: 'Voter ID Back Side',
    backDescription: 'Residential Address, Assembly Constituency & Electoral Officer Seal',
    iconName: 'FileText',
    expectedFrontFields: ['documentNumber', 'fullName', 'gender'],
    expectedBackFields: ['address', 'constituency'],
  },
  'PASSPORT': {
    type: 'PASSPORT',
    label: 'Indian Passport (Republic of India)',
    shortLabel: 'Passport',
    supportsBack: false,
    frontLabel: 'Passport Bio-Data Page',
    frontDescription: 'Passport Number, Full Name, Nationality, DOB, Expiry Date & MRZ zone',
    iconName: 'Globe',
    expectedFrontFields: ['documentNumber', 'fullName', 'nationality', 'dob', 'expiryDate'],
  },
  'COLLEGE_ID': {
    type: 'COLLEGE_ID',
    label: 'College / University Student ID',
    shortLabel: 'College ID',
    supportsBack: true,
    frontLabel: 'Student ID Front Side',
    frontDescription: 'Student Name, Roll/Student Number, Department & Course',
    backLabel: 'Student ID Back Side',
    backDescription: 'Emergency Contact, Address, Validity & Authority Signature',
    iconName: 'GraduationCap',
    expectedFrontFields: ['fullName', 'studentId', 'collegeName'],
    expectedBackFields: ['address'],
  },
  'EMPLOYEE_ID': {
    type: 'EMPLOYEE_ID',
    label: 'Corporate / Govt Employee ID',
    shortLabel: 'Employee ID',
    supportsBack: true,
    frontLabel: 'Employee ID Front Side',
    frontDescription: 'Employee Name, Employee ID Number, Company Name & Designation',
    backLabel: 'Employee ID Back Side',
    backDescription: 'Office Address, Blood Group & Emergency Contact',
    iconName: 'Briefcase',
    expectedFrontFields: ['fullName', 'employeeId', 'companyName'],
    expectedBackFields: ['address'],
  },
  'GOVT_EMPLOYEE_ID': {
    type: 'GOVT_EMPLOYEE_ID',
    label: 'Government Employee ID',
    shortLabel: 'Govt Employee ID',
    supportsBack: true,
    frontLabel: 'Govt ID Front Side',
    frontDescription: 'Official Name, Department, Designation & Official ID',
    backLabel: 'Govt ID Back Side',
    backDescription: 'Office Address & Issuing Authority',
    iconName: 'Building',
    expectedFrontFields: ['fullName', 'employeeId', 'department'],
    expectedBackFields: ['address'],
  },
  'PRIVATE_EMPLOYEE_ID': {
    type: 'PRIVATE_EMPLOYEE_ID',
    label: 'Private Employee ID',
    shortLabel: 'Private Employee ID',
    supportsBack: true,
    frontLabel: 'Corporate ID Front Side',
    frontDescription: 'Employee Name, Corporate ID, Company & Designation',
    backLabel: 'Corporate ID Back Side',
    backDescription: 'Company Address & Emergency Contacts',
    iconName: 'Briefcase',
    expectedFrontFields: ['fullName', 'employeeId', 'companyName'],
    expectedBackFields: ['address'],
  },
  'STUDENT_ID': {
    type: 'STUDENT_ID',
    label: 'School / Institution Student ID',
    shortLabel: 'Student ID',
    supportsBack: true,
    frontLabel: 'Student ID Front Side',
    frontDescription: 'Student Name, Class/Batch, Student ID Number',
    backLabel: 'Student ID Back Side',
    backDescription: 'Guardian Contact, Blood Group & Address',
    iconName: 'GraduationCap',
    expectedFrontFields: ['fullName', 'studentId'],
    expectedBackFields: ['address'],
  },
  'RC_BOOK': {
    type: 'RC_BOOK',
    label: 'Vehicle Registration Certificate (RC)',
    shortLabel: 'RC Book',
    supportsBack: true,
    frontLabel: 'RC Front Side',
    frontDescription: 'Registration No, Owner Name, Vehicle Model & Class',
    backLabel: 'RC Back Side',
    backDescription: 'Chassis No, Engine No, Hypothecation & RTO Seal',
    iconName: 'Car',
    expectedFrontFields: ['documentNumber', 'fullName'],
    expectedBackFields: [],
  },
  'OTHER': {
    type: 'OTHER',
    label: 'Other Identity Card / Document',
    shortLabel: 'Other Document',
    supportsBack: true,
    frontLabel: 'Document Front Side',
    frontDescription: 'Identity cardholder name, document ID number & photograph',
    backLabel: 'Document Back Side (Optional)',
    backDescription: 'Address details, additional terms, or verification barcode',
    iconName: 'FileText',
    expectedFrontFields: ['fullName', 'documentNumber'],
    expectedBackFields: ['address'],
  },
  'AUTOMATIC_DETECTION': {
    type: 'AUTOMATIC_DETECTION',
    label: 'Auto Detect Document Type',
    shortLabel: 'Auto Detect',
    supportsBack: true,
    frontLabel: 'Document Front Side',
    frontDescription: 'AI auto-detects Aadhaar, PAN, Driving Licence, Passport or Voter ID',
    backLabel: 'Document Back Side',
    backDescription: 'Back-side address or secondary verification',
    iconName: 'Sparkles',
    expectedFrontFields: ['fullName', 'documentNumber'],
    expectedBackFields: ['address'],
  },
  'AADHAAR_FRONT': {
    type: 'AADHAAR_FRONT',
    label: 'Aadhaar Card (Front Only)',
    shortLabel: 'Aadhaar Front',
    supportsBack: false,
    frontLabel: 'Aadhaar Front Side',
    frontDescription: 'Cardholder Name, 12-digit Aadhaar Number, DOB & Photo',
    iconName: 'ShieldCheck',
    expectedFrontFields: ['fullName', 'documentNumber', 'dob', 'gender'],
  },
  'AADHAAR_BACK': {
    type: 'AADHAAR_BACK',
    label: 'Aadhaar Card (Back Only)',
    shortLabel: 'Aadhaar Back',
    supportsBack: false,
    frontLabel: 'Aadhaar Back Side & Address',
    frontDescription: 'Multi-line Address, C/O, District, State, PIN Code & QR',
    iconName: 'MapPin',
    expectedFrontFields: ['address', 'pinCode', 'district', 'state'],
  },
  'OCI_CARD': {
    type: 'OCI_CARD',
    label: 'Overseas Citizen of India (OCI) Card',
    shortLabel: 'OCI Card',
    supportsBack: true,
    frontLabel: 'OCI Front Side',
    frontDescription: 'OCI Number, Holder Name, Nationality & Photo',
    backLabel: 'OCI Back Side',
    backDescription: 'Address in India / Abroad',
    iconName: 'Globe',
    expectedFrontFields: ['documentNumber', 'fullName', 'nationality'],
  },
  'NREGA_JOB_CARD': {
    type: 'NREGA_JOB_CARD',
    label: 'NREGA Job Card',
    shortLabel: 'NREGA Card',
    supportsBack: true,
    frontLabel: 'NREGA Front Side',
    frontDescription: 'Cardholder Name, Job Card No, Village & Panchayat',
    iconName: 'FileText',
    expectedFrontFields: ['documentNumber', 'fullName'],
  },
  'SENIOR_CITIZEN_CARD': {
    type: 'SENIOR_CITIZEN_CARD',
    label: 'Senior Citizen Card',
    shortLabel: 'Senior Citizen Card',
    supportsBack: true,
    frontLabel: 'Senior Card Front Side',
    frontDescription: 'Cardholder Name, DOB, Age & ID',
    iconName: 'FileText',
    expectedFrontFields: ['documentNumber', 'fullName', 'dob'],
  },
  'DISABILITY_ID_CARD': {
    type: 'DISABILITY_ID_CARD',
    label: 'Unique Disability ID (UDID)',
    shortLabel: 'Disability ID (UDID)',
    supportsBack: true,
    frontLabel: 'UDID Front Side',
    frontDescription: 'UDID Number, Name, Disability Type & Percentage',
    iconName: 'FileText',
    expectedFrontFields: ['documentNumber', 'fullName'],
  },
  'HEALTH_INSURANCE_CARD': {
    type: 'HEALTH_INSURANCE_CARD',
    label: 'Health / Ayushman Insurance Card',
    shortLabel: 'Health Card',
    supportsBack: true,
    frontLabel: 'Health Card Front Side',
    frontDescription: 'Policy/PMJAY ID, Beneficiary Name & Family Details',
    iconName: 'FileText',
    expectedFrontFields: ['documentNumber', 'fullName'],
  },
  'POLICE_ID': {
    type: 'POLICE_ID',
    label: 'Police Service Identity Card',
    shortLabel: 'Police ID',
    supportsBack: true,
    frontLabel: 'Police ID Front Side',
    frontDescription: 'Officer Name, Rank, Badge/Belt No & Unit',
    iconName: 'ShieldCheck',
    expectedFrontFields: ['fullName', 'documentNumber'],
  },
  'ARMY_ID': {
    type: 'ARMY_ID',
    label: 'Defence / Army Identity Card',
    shortLabel: 'Army / Defence ID',
    supportsBack: true,
    frontLabel: 'Defence ID Front Side',
    frontDescription: 'Service No, Rank, Name, Regiment/Unit',
    iconName: 'ShieldCheck',
    expectedFrontFields: ['fullName', 'documentNumber'],
  },
  'OTHER_GOVT_ID': {
    type: 'OTHER_GOVT_ID',
    label: 'Other Government ID Card',
    shortLabel: 'Other Govt ID',
    supportsBack: true,
    frontLabel: 'Govt ID Front Side',
    frontDescription: 'Holder Name, Government ID Number & Ministry/Dept',
    iconName: 'FileText',
    expectedFrontFields: ['fullName', 'documentNumber'],
  },
  'OTHER_IDENTITY_DOC': {
    type: 'OTHER_IDENTITY_DOC',
    label: 'Other Verified Identity Document',
    shortLabel: 'Other ID',
    supportsBack: true,
    frontLabel: 'Document Front Side',
    frontDescription: 'Cardholder Name & Document Identification Details',
    iconName: 'FileText',
    expectedFrontFields: ['fullName', 'documentNumber'],
  },
  'VISITOR_PASS': {
    type: 'VISITOR_PASS',
    label: 'Pre-issued Visitor Pass / QR Ticket',
    shortLabel: 'Visitor Pass',
    supportsBack: false,
    frontLabel: 'Visitor Pass & Barcode',
    frontDescription: 'Pass Number, Visitor Name & Host Approval Details',
    iconName: 'QrCode',
    expectedFrontFields: ['documentNumber', 'fullName'],
  },
  'UNKNOWN': {
    type: 'UNKNOWN',
    label: 'Unrecognized Identity Document',
    shortLabel: 'Unrecognized ID',
    supportsBack: true,
    frontLabel: 'Document Front Side',
    frontDescription: 'Document visual capture',
    iconName: 'FileText',
    expectedFrontFields: ['fullName', 'documentNumber'],
  },
};

export function getDocumentConfig(type: DocumentType): DocumentTypeConfig {
  return DOCUMENT_TYPE_CONFIGS[type] || DOCUMENT_TYPE_CONFIGS['OTHER'];
}

export function supportsBackSide(type: DocumentType): boolean {
  const config = getDocumentConfig(type);
  return config.supportsBack;
}
